# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2352d5ef6c9d467d3f300b024f04e462"
name = "product-upload-app"
handle = "product-upload-app-3"
application_url = "https://ae25-103-251-255-126.ngrok-free.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "sohail-app-dev.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://ae25-103-251-255-126.ngrok-free.app/auth/callback",
  "https://ae25-103-251-255-126.ngrok-free.app/auth/shopify/callback",
  "https://ae25-103-251-255-126.ngrok-free.app/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
